# Site settings
title: Page Type API
abbr: wp-papi
email: fredrik.forsmo@gmail.com
description: "Papi has a different approach on how to work with fields and page types in WordPress. The idea is coming from how Page Type Builder in EPiServer works and has been loved by the developers."
baseurl: ""
url: "http://wp-ptb.github.io"

# Build settings
markdown: kramdown
permalink: /:title

# Exclude
exclude: ['node_modules/']
