# Site settings
title: Page Type API
abbr: wp-papi
email: your-email@domain.com
description: "wp-papi for WordPress allows you create page types using the existing page post type or using custom post types. For those how have work with Page Types in EPiServer will recognize themselves."
baseurl: ""
url: "http://wp-ptb.github.io"

# Build settings
markdown: kramdown
permalink: /:title

# Exclude
exclude: ['node_modules/']
