# Site settings
title: WP Page Type Builder
abbr: WP-PTB
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://wp-ptb.github.io"

# Build settings
markdown: kramdown
permalink: /:title
